### ISSUE TITLE
Invalid API key? 

### ISSUE THREAD

**Issue by carks32** [glhrmv/motif#1]
Maybe I got something missed up but after someone tried to .np the bot would just put this.

```
   { error: 10,
        message: 'Invalid API key - You must be granted a valid key by last.fm'
} } }
```

**Comment by glhrmv** [comment]
Hi, I believe I just fixed this. Try pulling the new version and trying it out. Let me know.

**Comment by carks32** [comment]
Yeah, it's finally working! Though, you deleted the keys.js file but you still load it on the bot.js. 

Also, are you planning to add a way so the bot remembers your username?

**Comment by glhrmv** [comment]
I added the `keys.js` file back in, sorry about that.

I might rewrite the bot eventually, but I'm not planning on it currently. You're free to fork it, or contribute to this repo if you'd like.
